image: mcr.microsoft.com/playwright:v1.48.0-jammy

stages:
  - test

test_e2e:
  stage: test
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test --reporter=list
  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 1 day
